// Generated by CoffeeScript 2.7.0
(function () {
  var MessageEvents, hasUnicode, message, notString;
  ({
    notString
  } = require('types.js'));
  MessageEvents = require('message-events');
  message = new MessageEvents();
  message.format('error', function (text) {
    return {
      sender: 'has-unicode',
      type: 'error',
      text: text
    };
  });

  hasUnicode = function (string) {
    var ch, i, len, pos;

    if (notString(string)) {
      message.error('requires a string type argument');
    } else {
      for (pos = i = 0, len = string.length; i < len; pos = ++i) {
        ch = string[pos];

        if (string.charCodeAt(pos) > 127) {
          return true;
        }
      }
    }

    return false;
  };

  hasUnicode.onError = function (handler) {
    return message.on('error', handler);
  };

  module.exports = hasUnicode;
}).call(this);